### ISSUE TITLE
fsstat Task attribute error

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1006]
Seeing this in the latest release:
```
AttributeError
'NoneType' object has no attribute 'type_indicator'
Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/__init__.py", line 1005, in run_wrapper self.result = self.run(evidence, self.result) File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/fsstat.py", line 43, in run if evidence.path_spec.type_indicator == 'XFS': AttributeError: 'NoneType' object has no attribute 'type_indicator'
```

Full log from that Task:
```
2022-02-17 01:24:28 [INFO] Starting Task FsstatTask 48b091f178fa4a3e84d8fb97507d455b                                                                                                                       [7/1876]2022-02-17 01:24:28 [DEBUG] Starting pre-processor for evidence GoogleCloudDisk
2022-02-17 01:24:28 [DEBUG] Adding task 48b091f178fa4a3e84d8fb97507d455b into the resource state file for resource <redacted>.                                           2022-02-17 01:24:28 [DEBUG] The resource state file has been successfully updated.
2022-02-17 01:24:28 [INFO] Disk <redacted> already attached!
2022-02-17 01:24:28 [DEBUG] Pre-processing evidence GoogleCloudDisk is complete, and evidence is in state [MOUNTED: False, ATTACHED: True, DECOMPRESSED: False, CONTAINER_MOUNTED: False]
2022-02-17 01:24:28 [DEBUG] Starting pre-processor for evidence DiskPartition
2022-02-17 01:24:28 [WARNING] Could not find path_spec for location /p15                                                                                                                                           
2022-02-17 01:24:28 [INFO] Running command sudo losetup --show --find -r -o 4194304 --sizelimit 130023424 /dev/disk/by-id/<redacted>
2022-02-17 01:24:28 [DEBUG] Pre-processing evidence DiskPartition is complete, and evidence is in state [MOUNTED: False, ATTACHED: True, DECOMPRESSED: False, CONTAINER_MOUNTED: False]
2022-02-17 01:24:28 [DEBUG] Returning cached config from /etc/turbinia/turbinia.conf instead of reloading config
2022-02-17 01:24:28 [DEBUG] Updating Task FsstatTask in Datastore
2022-02-17 01:24:28 [ERROR] FsstatTask Task failed with exception: ['NoneType' object has no attribute 'type_indicator']
2022-02-17 01:24:28 [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/__init__.py", line 1005, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/fsstat.py", line 43, in run
    if evidence.path_spec.type_indicator == 'XFS':
AttributeError: 'NoneType' object has no attribute 'type_indicator'

2022-02-17 01:24:28 [DEBUG] Returning cached config from /etc/turbinia/turbinia.conf instead of reloading config
2022-02-17 01:24:28 [ERROR] FsstatTask Task failed with exception: ['NoneType' object has no attribute 'type_indicator']
2022-02-17 01:24:28 [INFO] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/__init__.py", line 1005, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/usr/local/lib/python3.8/dist-packages/turbinia-20220216-py3.8.egg/turbinia/workers/fsstat.py", line 43, in run
    if evidence.path_spec.type_indicator == 'XFS':
AttributeError: 'NoneType' object has no attribute 'type_indicator'

2022-02-17 01:24:28 [DEBUG] Checking TurbiniaTaskResult for pickle serializability
2022-02-17 01:24:28 [DEBUG] Checking TurbiniaTaskResult for JSON serializability
2022-02-17 01:24:28 [INFO] Result check: Successful
2022-02-17 01:24:28 [DEBUG] No state_manager initialized, not updating Task info
2022-02-17 01:24:28 [WARNING] Trying last ditch attempt to close result
2022-02-17 01:24:28 [INFO] Trying last ditch attempt to close result
2022-02-17 01:24:28 [INFO] Task Result was auto-closed from task executor on turbinia-worker-7fd8ff76d9-7bvjr likely due to previous failures.  Previous status: [FsstatTask Task failed with exception: ['NoneType
' object has no attribute 'type_indicator']]
2022-02-17 01:24:28 [INFO] Task Result was auto-closed from task executor on turbinia-worker-7fd8ff76d9-7bvjr likely due to previous failures.  Previous status: [FsstatTask Task failed with exception: ['NoneType
' object has no attribute 'type_indicator']]
2022-02-17 01:24:28 [INFO] Starting post-processor for evidence DiskPartition
2022-02-17 01:24:28 [DEBUG] Evidence state: [MOUNTED: False, ATTACHED: True, DECOMPRESSED: False, CONTAINER_MOUNTED: False]
2022-02-17 01:24:28 [INFO] Running: sudo losetup -d /dev/loop0
2022-02-17 01:24:29 [INFO] Running: sudo losetup -a
2022-02-17 01:24:29 [INFO] losetup device [/dev/loop0] deleted.
2022-02-17 01:24:29 [INFO] Starting post-processor for evidence GoogleCloudDisk
2022-02-17 01:24:29 [DEBUG] Evidence state: [MOUNTED: False, ATTACHED: True, DECOMPRESSED: False, CONTAINER_MOUNTED: False]
2022-02-17 01:24:29 [DEBUG] Last task 48b091f178fa4a3e84d8fb97507d455b remaining. Removing resource <redacted> from the resource state file.
2022-02-17 01:24:29 [DEBUG] The resource state file has been successfully updated.
2022-02-17 01:24:29 [DEBUG] Returning cached config from /etc/turbinia/turbinia.conf instead of reloading config
2022-02-17 01:24:30 [INFO] Detaching disk <redacted> from instance gke-turbinia-prod-cluste-default-pool-eb936c58-lv66
2022-02-17 01:24:36 [INFO] Block device /dev/disk/by-id/<redacted> is no longer attached
2022-02-17 01:24:36 [DEBUG] Not copying source file /var/tmp/b82801fb483744bfa65a4b90fa1724ab/1645061068-48b091f178fa4a3e84d8fb97507d455b-FsstatTask/worker-log.txt already in output dir /var/tmp/b82801fb483744bf
a65a4b90fa1724ab/1645061068-48b091f178fa4a3e84d8fb97507d455b-FsstatTask
2022-02-17 01:24:36 [INFO] Writing /var/tmp/b82801fb483744bfa65a4b90fa1724ab/1645061068-48b091f178fa4a3e84d8fb97507d455b-FsstatTask/worker-log.txt to GCS path output/b82801fb483744bfa65a4b90fa1724ab/1645061068-4
8b091f178fa4a3e84d8fb97507d455b-FsstatTask/worker-log.txt
```

**Comment by aarontp** [comment]
@dfjxs Any chance you could take a look at this?

**Comment by dfjxs** [comment]
Sure, will take a look.
