### ISSUE TITLE
The value of property "data" is longer than 1048487 bytes. 

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1009]
Looks like the traceback is happening in gcp libraries, are we adding a new datatype that we need to adjust for? 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 72, in _wrap_callback_errors
    callback(message)
  File "/usr/local/lib/python3.8/dist-packages/psq/queue.py", line 128, in _pubsub_message_callback
    task_callback(task)
  File "/usr/local/lib/python3.8/dist-packages/psq/worker.py", line 50, in run_task
    task.execute(self.queue)
  File "/usr/local/lib/python3.8/dist-packages/psq/task.py", line 101, in execute
    queue.storage.put_task(self)
  File "/usr/local/lib/python3.8/dist-packages/psq/datastore_storage.py", line 63, in put_task
    self.datastore.put(entity)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/datastore/client.py", line 570, in put
    self.put_multi(entities=[entity], retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/datastore/client.py", line 610, in put_multi
    current.commit(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/datastore/batch.py", line 300, in commit
    self._commit(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/datastore/batch.py", line 257, in _commit
    commit_response_pb = self._client._datastore_api.commit(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/datastore_v1/services/datastore/client.py", line 627, in commit
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 The value of property "data" is longer than 1048487 bytes. 
```

**Comment by aarontp** [comment]
I think it might have hit some kind of limit trying to write something >1MB.  It must have been a very large report.

**Comment by aarontp** [comment]
Yeah, apparently an entity has a 1MB limit: https://cloud.google.com/datastore/docs/concepts/limits .  Maybe for now we can truncate the report and add a counter for that condition.  Long term we'll move away from datastore, but we can make those changes for now and monitor how often it happens to see if we need to do anything further.
