### ISSUE TITLE
Pydantic JSON method no longer supports keyword arguments

### ISSUE THREAD

**Issue by jleaniz** [google/turbinia#1304]
```
2023-07-13 19:21:13,281:ERROR:Error retrieving requests summary: `dumps_kwargs` keyword arguments are no longer supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/turbinia-20230316.dev56+gda3d799-py3.10.egg/turbinia/api/routes/request.py", line 50, in get_requests_summary
    response_json = requests_summary.json(sort_keys=True)
  File "/usr/local/lib/python3.10/dist-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 926, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
```

**Comment by jleaniz** [comment]
Fixed in #1312
