### ISSUE TITLE
Review Python dependencies requirements

### ISSUE THREAD

**Issue by jleaniz** [google/turbinia#1311]
Now that the API server has been implemented, we can start reviewing which dependencies we need and remove some pinned versions that cause problems.

For exmaple google-auth<2.0.0.dev0 conflicts with the google-auth library required by the turbinia-client package and causes the following error if you install turbinia and turbinia-client on the same Python environment.

```
Traceback (most recent call last):
  File "/usr/local/bin/turbinia-client", line 5, in <module>
    from turbinia_client.turbiniacli_tool import main
  File "/usr/local/lib/python3.10/dist-packages/turbinia_client/turbiniacli_tool.py", line 24, in <module>
    from turbinia_client.turbiniacli import TurbiniaCli
  File "/usr/local/lib/python3.10/dist-packages/turbinia_client/turbiniacli.py", line 26, in <module>
    from turbinia_client.helpers import auth_helper
  File "/usr/local/lib/python3.10/dist-packages/turbinia_client/helpers/auth_helper.py", line 21, in <module>
    from google_auth_oauthlib import flow
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/interactive.py", line 27, in <module>
    import google_auth_oauthlib.flow
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/flow.py", line 68, in <module>
    import google_auth_oauthlib.helpers
  File "/usr/local/lib/python3.10/dist-packages/google_auth_oauthlib/helpers.py", line 26, in <module>
    from google.auth import external_account_authorized_user
ImportError: cannot import name 'external_account_authorized_user' from 'google.auth' (/usr/local/lib/python3.10/dist-packages/google/auth/__init__.py)
```

**Comment by aarontp** [comment]
I wonder if it makes sense to break out the dependencies for the old architecture into a forked requirements.txt and then have an isolated, new clean requirements/setup for only the new architecture for now?

**Comment by jleaniz** [comment]
Following offline chat, I'll look into using Poetry to manage dependencies.
