### ISSUE TITLE
can't run_tests.py

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#236]
$ virtualenv ~/venvs/turbinia-test
$ source ~/venvs/turbinia-test/bin/activate
$ cd ~/src/turbinia/ ; git pull origin master
$ pip install -e ~/src/turbinia/
$ python run_tests.py
```
<SNIP, more import errors before>
======================================================================
ERROR: Failure: ImportError (No module named cloud)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/romaing/src/turbinia/turbinia/state_manager_test.py", line 26, in <module>
    from turbinia.workers import TurbiniaTask
  File "/home/romaing/src/turbinia/turbinia/workers/__init__.py", line 33, in <module>
    from turbinia import output_manager
  File "/home/romaing/src/turbinia/turbinia/output_manager.py", line 31, in <module>
    from google.cloud import storage
ImportError: No module named cloud

----------------------------------------------------------------------
Ran 12 tests in 0.059s

FAILED (errors=7)
Traceback (most recent call last):
  File "run_tests.py", line 22, in <module>
    'nosetests', '-vv', '--with-coverage', '--cover-package=turbinia'
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vv', '--with-coverage', '--cover-package=turbinia']' returned non-zero exit status 1
```
though in the same virtualenv, I can do:
`$ python -c "from google.cloud import storage"`
with no error.
Is there something weird with nosetest?

**Comment by aarontp** [comment]
Do you have a PYTHONPATH or other variable in your environment that is
adding to the virtualenv paths?  I would make sure those are unset.

Also, just FYI, you'll need to install the [dev] packages (pip install -e
.[dev]) if you haven't already, but I think that is separate from the issue
you're seeing here.

**Comment by rgayon** [comment]
Same result after unset PYTHONPATH.

Tests run (and pass) with :
pip install -e ~/src/turbinia//.[dev]
(and manually installing celery)
closing

**Comment by aarontp** [comment]
FYI, pip install -e .[local] should pick up the celery requirements.
