### ISSUE TITLE
Turbiniactl --version or --help parses the config file (and crashes if invalid)

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#267]
Filing this because I was looking if a --config flag existed so I tested turbiniactl --help

$ turbiniactl --version
Traceback (most recent call last):
  File "/home/romaing/venvs/turbinia-test/bin/turbiniactl", line 11, in <module>
    load_entry_point('turbinia==20180620', 'console_scripts', 'turbiniactl')()
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/turbiniactl.py", line 28, in <module>
    from turbinia.client import TurbiniaClient
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/client.py", line 29, in <module>
    from turbinia import task_manager
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/task_manager.py", line 23, in <module>
    from turbinia import evidence
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/evidence.py", line 29, in <module>
    config.LoadConfig()
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/config/__init__.py", line 104, in LoadConfig
    ValidateAndSetConfig(_config)
  File "/home/romaing/venvs/turbinia-test/local/lib/python2.7/site-packages/turbinia-20180620-py2.7.egg/turbinia/config/__init__.py", line 115, in ValidateAndSetConfig
    'No config attribute {0:s}:{1:s}'.format(_config.configSource, var))
turbinia.config.TurbiniaConfigException: No config attribute /home/romaing/.turbiniarc:LOCK_FILE

**Comment by aarontp** [comment]
Hrm, yeah, I guess evidence.py does a config load at the module level, so when evidence is imported it tries to load and then fails if there are problems.  I guess the fix here is to move the config load out of the module level and down to where the config is required.

**Comment by aarontp** [comment]
Fixed by #427
