### ISSUE TITLE
Cloud dependencies broken upstream... again

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#325]
======================================================================
ERROR: Failure: ImportError (No module named iam)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/google/turbinia/turbinia/jobs/__init__.py", line 16, in <module>
    from turbinia.jobs import grep
  File "/home/travis/build/google/turbinia/turbinia/jobs/grep.py", line 24, in <module>
    from turbinia.workers.grep import GrepTask
  File "/home/travis/build/google/turbinia/turbinia/workers/__init__.py", line 33, in <module>
    from turbinia import output_manager
  File "/home/travis/build/google/turbinia/turbinia/output_manager.py", line 31, in <module>
    from google.cloud import storage
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
    from google.cloud.storage.blob import Blob
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 54, in <module>
    from google.api_core.iam import Policy
ImportError: No module named iam

**Comment by aarontp** [comment]
Looks like google-cloud-storage was updated in:
https://github.com/googleapis/google-cloud-python/pull/6741

Which just got released as 1.13.1:
https://pypi.org/project/google-cloud-storage/#history
