### ISSUE TITLE
HadoopAnalysisTask errors

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#330]
Now that the new artifacts and new Plaso have been released, we are getting a new error from the HadoopAnalysisTask.  Error is: `Unsupported artifact definition source type: "PATH"` 

Full trace of manual run with the same flags as the task executes:
```
$ image_export.py --artifact_filters HadoopAppRoot --write /tmp/artifacts/ --partitions all /dev/sdb
2018-12-14 18:36:02,020 [INFO] (MainProcess) PID:4328 <data_location> Determined data location: /home/turbinia/env/pipenv/local/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/share/plaso
2018-12-14 18:36:02,021 [INFO] (MainProcess) PID:4328 <artifact_definitions> Determined artifact definitions path: /home/turbinia/env/pipenv/share/artifacts
Export started.
Extracting file entries from: TSK:/
2018-12-14 18:36:04,021 [WARNING] (MainProcess) PID:4328 <artifact_filters> Unsupported artifact definition source type: "PATH"
Traceback (most recent call last):
  File "/home/turbinia/env/pipenv/bin/image_export.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20181127', 'image_export.py')
  File "/home/turbinia/env/pipenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/turbinia/env/pipenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home/turbinia/env/pipenv/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/EGG-INFO/scripts/image_export.py", line 57, in <module>
    if not Main():
  File "/home/turbinia/env/pipenv/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/EGG-INFO/scripts/image_export.py", line 36, in Main
    tool.ProcessSources()
  File "/home/turbinia/env/pipenv/local/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/plaso/cli/image_export_tool.py", line 768, in ProcessSources
    skip_duplicates=self._skip_duplicates)
  File "/home/turbinia/env/pipenv/local/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/plaso/cli/image_export_tool.py", line 331, in _ExtractWithFilter
    self._knowledge_base, artifact_filters, filter_file)
  File "/home/turbinia/env/pipenv/local/lib/python2.7/site-packages/plaso-20181127-py2.7.egg/plaso/engine/engine.py", line 333, in BuildFilterFindSpecs
    'Error processing filters, no valid specifications built.')
RuntimeError: Error processing filters, no valid specifications built.
```

Error seems to happen from here:
https://github.com/log2timeline/plaso/blob/e6d449bd8b55890733f524d262fe828350a34d3d/plaso/engine/artifact_filters.py#L131

@rgayon Can you take a look at this?  I'm not sure how this worked before. 

cc: @rbdebeer since he touched artifact_filters.py last and may also have some ideas.

**Comment by rbdebeer** [comment]
PATH artifact type is not implemented here:
https://github.com/log2timeline/plaso/blob/40026c42e46e2434569789c2dfd4c14847aea427/plaso/engine/artifact_filters.py#L83

**Comment by aarontp** [comment]
This is working now after the artifact type was changed to a type that `image_export.py` supports.
