### ISSUE TITLE
report_priority TypeError

### ISSUE THREAD

**Issue by ericzinnikas** [google/turbinia#380]
Seems like when a job first starts, `turbiniactl status` can't handle if only 0 or 1 tasks exist (maybe)?

```
(turbinia) [ericwz@dev ~] turbiniactl status -r 4c77ecac831f420a8ea30e5a9946e47d
[INFO] Turbinia version: 20181004
Traceback (most recent call last):
  File "/home/ericwz/virtualenvs/turbinia/bin/turbiniactl", line 11, in <module>
    load_entry_point('turbinia==20181004', 'console_scripts', 'turbiniactl')()
  File "/home/ericwz/virtualenvs/turbinia/lib/python3.6/site-packages/turbinia/turbiniactl.py", line 409, in main
    priority_filter=args.priority_filter))
  File "/home/ericwz/virtualenvs/turbinia/lib/python3.6/site-packages/turbinia/client.py", line 333, in format_task_status
    task_results = sorted(task_results, key=itemgetter('report_priority'))
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
(turbinia) [ericwz@dev ~] turbiniactl status -r 4c77ecac831f420a8ea30e5a9946e47d
[INFO] Turbinia version: 20181004
Traceback (most recent call last):
  File "/home/ericwz/virtualenvs/turbinia/bin/turbiniactl", line 11, in <module>
    load_entry_point('turbinia==20181004', 'console_scripts', 'turbiniactl')()
  File "/home/ericwz/virtualenvs/turbinia/lib/python3.6/site-packages/turbinia/turbiniactl.py", line 409, in main
    priority_filter=args.priority_filter))
  File "/home/ericwz/virtualenvs/turbinia/lib/python3.6/site-packages/turbinia/client.py", line 333, in format_task_status
    task_results = sorted(task_results, key=itemgetter('report_priority'))
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

After a while it works:
```
(turbinia) [ericwz@dev ~] turbiniactl status -r 4c77ecac831f420a8ea30e5a9946e47d
[INFO] Turbinia version: 20181004


# Turbinia report 4c77ecac831f420a8ea30e5a9946e47d
* Processed 12 Tasks for user ericwz

# High Priority Tasks
* None

# Successful Tasks
* StringsAsciiTask: Completed successfully in 0:00:32.117996 on dev
* StringsUnicodeTask: Completed successfully in 0:00:10.367761 on dev
* StatTask: Completed successfully in 0:00:00.020264 on dev

# Failed Tasks
* GrepTask: No patterns supplied, exit task
* FileArtifactExtractionTask: image_export.py failed for artifact NginxAccessLogs.
* HadoopAnalysisTask: image_export.py failed.
* FileArtifactExtractionTask: image_export.py failed for artifact SshdConfigFile.
* PlasoTask: Execution of [['log2timeline.py', '--status_view', 'none', '--hashers', 'all', '--partition', 'all', '--vss_stores', 'all', '--logfile', '/var/tmp/1555625789-4345f334692748ad9112be58d796548a-PlasoTask/4345f334692748ad9112be58d796548a.log', '/tmp/1555625789-4345f334692748ad9112be58d796548a-PlasoTask/4345f334692748ad9112be58d796548a.plaso', '/test.Ex01]] failed with status 1
* FileArtifactExtractionTask: image_export.py failed for artifact TomcatFiles.
* FileArtifactExtractionTask: image_export.py failed for artifact ApacheAccessLogs.
* FileArtifactExtractionTask: image_export.py failed for artifact GKEDockerContainerLogs.
* GrepTask: No patterns supplied, exit task

# Scheduled or Running Tasks
* None
[INFO] Done.
```

**Comment by aarontp** [comment]
Ah, I bet this is because of some recent code that I added for the report generation.  For status updates it tries to sort the tasks by a `report_priority` key, and if that key doesn't exist, then it errors.  I'll take a look, thanks.

**Comment by aarontp** [comment]
This should be fixed now.  LMK if you still see problems.
