### ISSUE TITLE
Loop devices causing permission problems in Tasks

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#467]
Because of the changes to disk based pre-processors in #388 the Evidence paths now point to loop devices instead of the original file/device path.   Because not all of the subprocesses from the Tasks use sudo, these processes likely won't have access to the loop devices.   This causes some tasks like the Plaso and strings tasks to fail:

```
[INFO] Starting Task JenkinsAnalysisTask a85ce87bf0d0492bb8cbc23935ffdce6
[INFO] Running command sudo losetup --show --find -P -r /home/redacted/Documents/test-small.img
[INFO] Running ['lsblk', '/dev/loop7', '-f', '-o', 'FSTYPE', '-n']
[INFO] Running: sudo mount -o ro /dev/loop7 /mnt/turbinia-mounts/turbiniajskjliep
2019-12-05 12:44:40,462 [INFO] (MainProcess) PID:90772 <data_location> Determined data location: /usr/share/plaso
2019-12-05 12:44:40,463 [INFO] (MainProcess) PID:90772 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Filters:
names: config.xml
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/dfvfs/file_io/os_file_io.py", line 62, in _Open
is_device = pysmdev.check_device(location)
OSError: pysmdev_check_device: unable to check device. libcfile_file_open_with_error_code: access denied to file: /dev/loop7. libcfile_file_open: unable to open file. libsmdev_check_device: unable to open file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/image_export.py", line 77, in <module>
if not Main():
File "/usr/bin/image_export.py", line 52, in Main
tool.ProcessSources()
File "/usr/lib/python3/dist-packages/plaso/cli/image_export_tool.py", line 800, in ProcessSources
scan_context = self.ScanSource(self._source_path)
File "/usr/lib/python3/dist-packages/plaso/cli/storage_media_tool.py", line 1152, in ScanSource
self._source_scanner.Scan(scan_context)
File "/usr/lib/python3/dist-packages/dfvfs/helpers/source_scanner.py", line 662, in Scan
self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
File "/usr/lib/python3/dist-packages/dfvfs/helpers/source_scanner.py", line 428, in _ScanNode
source_path_spec = self.ScanForStorageMediaImage(scan_node.path_spec)
File "/usr/lib/python3/dist-packages/dfvfs/helpers/source_scanner.py", line 743, in ScanForStorageMediaImage
source_path_spec, resolver_context=self._resolver_context)
File "/usr/lib/python3/dist-packages/dfvfs/analyzer/analyzer.py", line 338, in GetStorageMediaImageTypeIndicators
resolver_context=resolver_context)
File "/usr/lib/python3/dist-packages/dfvfs/analyzer/analyzer.py", line 183, in _GetTypeIndicators
path_spec, resolver_context=resolver_context)
File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 112, in OpenFileObject
file_object.open(path_spec=path_spec_object)
File "/usr/lib/python3/dist-packages/dfvfs/file_io/file_io.py", line 76, in open
self._Open(path_spec=path_spec, mode=mode)
File "/usr/lib/python3/dist-packages/dfvfs/file_io/os_file_io.py", line 78, in _Open
location, exception_string))
dfvfs.lib.errors.AccessError: Access denied to file: /dev/loop7 with error: pysmdev_check_device: unable to check device. libcfile_file_open_with_error_code: access denied to file: /dev/loop7. libcfile_file_open: unable to open file. libsmdev_check_device: unable to open file.
```

**Comment by aarontp** [comment]
The work around for this is to add the Turbinia user to the `disk` group.

**Comment by aarontp** [comment]
FYI: @rgayon @wajihyassine

**Comment by aarontp** [comment]
We are requiring Turbinia to have disk privileges (ie. added to disk group) now, so this is no longer an issue.
