### ISSUE TITLE
JenkinsAnalysisTask Task failed with exception: [john the ripper failed.]

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#472]
Keep running into the exception below with the JenkinsAnalysisTask failing to find the directory 'john':'john'.
```
[ERROR] JenkinsAnalysisTask Task failed with exception: [john the ripper failed.]
[ERROR] Traceback (most recent call last):
  File "/turbinia/turbinia/lib/utils.py", line 128, in bruteforce_password_hashes
    child = subprocess.Popen(cmd, stdout=devnull, stderr=devnull)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'john': 'john'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/turbinia/turbinia/workers/__init__.py", line 637, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/turbinia/turbinia/workers/analysis/jenkins.py", line 83, in run
    (report, priority, summary) = self.analyze_jenkins(version, credentials)
  File "/turbinia/turbinia/workers/analysis/jenkins.py", line 163, in analyze_jenkins
    weak_passwords = bruteforce_password_hashes(credentials_registry.keys())
  File "/turbinia/turbinia/lib/utils.py", line 136, in bruteforce_password_hashes
    raise TurbiniaException('john the ripper failed.')
turbinia.TurbiniaException: john the ripper failed.

[ERROR] JenkinsAnalysisTask Task failed with exception: [john the ripper failed.]
[INFO] Traceback (most recent call last):
  File "/turbinia/turbinia/lib/utils.py", line 128, in bruteforce_password_hashes
    child = subprocess.Popen(cmd, stdout=devnull, stderr=devnull)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'john': 'john'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/turbinia/turbinia/workers/__init__.py", line 637, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/turbinia/turbinia/workers/analysis/jenkins.py", line 83, in run
    (report, priority, summary) = self.analyze_jenkins(version, credentials)
  File "/turbinia/turbinia/workers/analysis/jenkins.py", line 163, in analyze_jenkins
    weak_passwords = bruteforce_password_hashes(credentials_registry.keys())
  File "/turbinia/turbinia/lib/utils.py", line 136, in bruteforce_password_hashes
    raise TurbiniaException('john the ripper failed.')
turbinia.TurbiniaException: john the ripper failed.
```

**Comment by wajihyassine** [comment]
Ended up being that I didn't have john the ripper installed. Adding john the ripper to the list of dependency checks and closing this one out.
