### ISSUE TITLE
Better error handling in postprocessors

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#496]
Besides something like #485, we should add some better error handling to postprocessors that run after preprocessors that fail because the error is non-obvious.  We should at least check that the object is not `None` before calling:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "turbinia/workers/__init__.py", line 665, in run_wrapper
    evidence.preprocess(self.tmp_dir)
  File "//turbinia/evidence.py", line 238, in preprocess
    self._preprocess(tmp_dir)
  File "/turbinia/evidence.py", line 382, in _preprocess
    self.source_path)
  File "/turbinia/processors/mount_local.py", line 67, in PreprocessLosetup
    raise TurbiniaException('Could not set losetup devices {0!s}'.format(e))
turbinia.TurbiniaException: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-P', '-r', '/images/test-small.img']' returned non-zero exit status 1.

[DEBUG] Checking TurbiniaTaskResult for serializability
[ERROR] Error pickling TurbiniaTaskResult object. Returning a new result with the pickling error, and all previous result data will be lost. Pickle Error: Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
[DEBUG] Returning cached config from .turbiniarc instead of reloading config
[DEBUG] Returning cached config from .turbiniarc instead of reloading config
[INFO] Error pickling TurbiniaTaskResult object. Returning a new result with the pickling error, and all previous result data will be lost. Pickle Error: Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
[ERROR] Task 79d6b6aa2bc24ace9b65d6339640212b failed.
Traceback (most recent call last):
  File "turbinia/workers/__init__.py", line 194, in close
    self.input_evidence.postprocess()
AttributeError: 'NoneType' object has no attribute 'postprocess'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/share/virtualenvs/turbinia-docs-UjHQSp4l/lib/python3.7/site-packages/psq/task.py", line 90, in execute
    result = self.call_func()
  File ".local/share/virtualenvs/turbinia-docs-UjHQSp4l/lib/python3.7/site-packages/psq/task.py", line 104, in call_func
    return self.f(*self.args, **self.kwargs)
  File "turbinia/task_manager.py", line 83, in task_runner
    return obj.run_wrapper(*args, **kwargs)
  File "turbinia/workers/__init__.py", line 709, in run_wrapper
    self.result = self.validate_result(self.result)
  File "turbinia/workers/__init__.py", line 599, in validate_result
    result.close(self, success=False, status=bad_message)
  File "turbinia/workers/__init__.py", line 201, in close
    self.input_evidence.name, exception)
AttributeError: 'NoneType' object has no attribute 'name'
[ERROR] Task 79d6b6aa2bc24ace9b65d6339640212b failed.
Traceback (most recent call last):
  File "turbinia/workers/__init__.py", line 194, in close
    self.input_evidence.postprocess()
AttributeError: 'NoneType' object has no attribute 'postprocess'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/share/virtualenvs/turbinia-docs-UjHQSp4l/lib/python3.7/site-packages/psq/task.py", line 90, in execute
    result = self.call_func()
  File ".local/share/virtualenvs/turbinia-docs-UjHQSp4l/lib/python3.7/site-packages/psq/task.py", line 104, in call_func
    return self.f(*self.args, **self.kwargs)
  File "turbinia/task_manager.py", line 83, in task_runner
    return obj.run_wrapper(*args, **kwargs)
  File "turbinia/workers/__init__.py", line 709, in run_wrapper
    self.result = self.validate_result(self.result)
  File "turbinia/workers/__init__.py", line 599, in validate_result
    result.close(self, success=False, status=bad_message)
  File "turbinia/workers/__init__.py", line 201, in close
    self.input_evidence.name, exception)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by aarontp** [comment]
The above error is fixed in #485 .  It also has better error handling/checking for processors.
