### ISSUE TITLE
Package conflicts when deploying HEAD via terraform

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#503]
When pointing the Forseti Terraform configs at HEAD the server and workers are giving errors.  At least the dependencies.txt seems to be the same version.

```
Traceback (most recent call last):
  File "/usr/local/bin/turbiniactl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 39.0.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=40.3.0'), set(['google-auth']))
```

**Comment by aarontp** [comment]
FTR, this only happens when deploying from terraform for some reason.  Normal deployment seems OK.

**Comment by aarontp** [comment]
I just re-tested this, and this has been fixed since this time.
