### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'docker' distribution was not found and is required by turbinia

### ISSUE THREAD

**Issue by joachimmetz** [google/turbinia#542]
While working https://github.com/google/turbinia/pull/537

```
/usr/bin/turbiniactl -S server
Traceback (most recent call last):
  File "/usr/bin/turbiniactl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker' distribution was not found and is required by turbinia
```

```
# This will enable the usage of docker containers for the worker.
DOCKER_ENABLED = False
```

Is docker a required dependency or does need to be handled this more gracefully?

**Comment by joachimmetz** [comment]
I see docker was added to requirements.txt in a3508eefb917994b670af8f5620a5d02ac6ac6f8.

**Comment by joachimmetz** [comment]
@aarontp per our conversation, this is not urgent

**Comment by aarontp** [comment]
@wajihyassine Maybe we can selectively import this if the option is enabled in the config?

**Comment by wajihyassine** [comment]
Yeah that'd work, can assign this issue to myself to implement.

**Comment by wajihyassine** [comment]
Releasing to wild for to be picked up given other constraints
