### ISSUE TITLE
Hadoop task failing

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#552]
Hadoop tasks are failing in the current release branch version. I think we may have fixed this in HEAD already and may need to backport something.

```
[INFO] Starting Task HadoopAnalysisTask c0c9360636964f8d89461d600ad1dad2
[INFO] Attaching disk turbinia-dev-copy-20191030082558 to instance turbinia-worker-758ce47688b38d5f-2
[INFO] Attaching turbinia-dev-copy-20191030082558 to VM turbinia-worker-758ce47688b38d5f-2 in READ_ONLY mode
[INFO] Block device /dev/disk/by-id/google-turbinia-dev-copy-20191030082558 successfully attached
2020-06-16 11:31:26,714 [INFO] (MainProcess) PID:6419 <data_location> Determined data location: /usr/share/plaso
2020-06-16 11:31:26,715 [INFO] (MainProcess) PID:6419 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/manager.py", line 158, in CollectFromFileSystem
    knowledge_base, artifact_definition, searcher, file_system)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/interface.py", line 80, in Collect
    source.separator)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/interface.py", line 134, in _ParsePathSpecification
    self._ParseFileEntry(knowledge_base, file_entry)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/interface.py", line 168, in _ParseFileEntry
    file_object = file_entry.GetFileObject()
  File "/usr/lib/python3/dist-packages/dfvfs/vfs/tsk_file_entry.py", line 813, in GetFileObject
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python3/dist-packages/dfvfs/resolver/resolver.py", line 114, in OpenFileObject
    file_object.open(path_spec=path_spec_object)
  File "/usr/lib/python3/dist-packages/dfvfs/file_io/file_io.py", line 76, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/lib/python3/dist-packages/dfvfs/file_io/tsk_file_io.py", line 131, in _Open
    raise IOError('Not a regular file.')
OSError: Not a regular file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/cli/image_export_tool.py", line 532, in _PreprocessSources
    resolver_context=self._resolver_context)
  File "/usr/lib/python3/dist-packages/plaso/engine/engine.py", line 272, in PreprocessSources
    self.knowledge_base)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/manager.py", line 320, in RunPlugins
    artifacts_registry, knowledge_base, searcher, file_system)
  File "/usr/lib/python3/dist-packages/plaso/preprocessors/manager.py", line 163, in CollectFromFileSystem
    preprocess_plugin.ARTIFACT_DEFINITION_NAME, exception))
  File "/usr/lib/python3.6/logging/__init__.py", line 1320, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3/dist-packages/plaso/lib/loggers.py", line 38, in _open
    self.baseFilename, mode=self.mode, encoding=self.encoding)
  File "/usr/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/image_export-20200616T113126.log.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/image_export.py", line 87, in <module>
    if not Main():
  File "/usr/bin/image_export.py", line 57, in Main
    tool.ProcessSources()
  File "/usr/lib/python3/dist-packages/plaso/cli/image_export_tool.py", line 823, in ProcessSources
    skip_duplicates=self._skip_duplicates)
  File "/usr/lib/python3/dist-packages/plaso/cli/image_export_tool.py", line 355, in _ExtractWithFilter
    self._PreprocessSources(extraction_engine)
  File "/usr/lib/python3/dist-packages/plaso/cli/image_export_tool.py", line 535, in _PreprocessSources
    logger.error('Unable to preprocess with error: {0!s}'.format(exception))
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/usr/lib/python3/dist-packages/plaso/lib/loggers.py", line 38, in _open
    self.baseFilename, mode=self.mode, encoding=self.encoding)
  File "/usr/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: '/image_export-20200616T113126.log.gz'
[INFO] image_export.py failed.
[INFO] Detaching disk turbinia-dev-copy-20191030082558 from instance turbinia-worker-758ce47688b38d5f-2
[INFO] Detaching turbinia-dev-copy-20191030082558 from VM turbinia-worker-758ce47688b38d5f-2
[INFO] Block device /dev/disk/by-id/google-turbinia-dev-copy-20191030082558 is no longer attached
[INFO] Writing /var/lib/turbinia/1592307076-c0c9360636964f8d89461d600ad1dad2-HadoopAnalysisTask/worker-log.txt to GCS path output/1592307076-c0c9360636964f8d89461d600ad1dad2-HadoopAnalysisTask/worker-log.txt
```

**Comment by aarontp** [comment]
Fixed with new relesae.
