### ISSUE TITLE
DockerContainersEnumerationTask fails

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#666]
```
DockerContainersEnumerationTask: Task Result was auto-closed from task executor on turbinia-worker-4b732fb3879dbc15-0 likely due to previous failures.  Previous status: [DockerContainersEnumerationTask Task failed with exception: [Evidence GoogleCloudDisk:evidence-disk-1-20201204114002-d8f1d504-copy:None being processed by Task DockerContainersEnumerationTask requires Evidence to be in state MOUNTED, but earlier pre-processors may have failed.  Current state is [MOUNTED: False, ATTACHED: True, PARENT_MOUNTED: False, PARENT_ATTACHED: False, DECOMPRESSED: False, DOCKER_MOUNTED: False]. See previous logs for more information.]]
```

**Comment by hacktobeer** [comment]
[worker.log](https://github.com/google/turbinia/files/5642504/worker.log)

**Comment by hacktobeer** [comment]
Some more detailed logs from the worker:
```
[INFO] Starting Task DockerContainersEnumerationTask 3132ade0d8a449d79eff9bdde70817e7
[INFO] Attaching disk evidence-disk-1-20201204114002-d8f1d504-copy to instance turbinia-worker-4b732fb3879dbc15-0
[2020-12-04 11:42:05,714] [libcloudforensics.providers.gcp.internal.compute] INFO     project:ramses-test5 Attachin
g evidence-disk-1-20201204114002-d8f1d504-copy to VM turbinia-worker-4b732fb3879dbc15-0 in READ_ONLY mode
[INFO] project:ramses-test5 Attaching evidence-disk-1-20201204114002-d8f1d504-copy to VM turbinia-worker-4b732fb387
9dbc15-0 in READ_ONLY mode
[INFO] project:ramses-test5 Attaching evidence-disk-1-20201204114002-d8f1d504-copy to VM turbinia-worker-4b732fb387
9dbc15-0 in READ_ONLY mode
[INFO] Block device /dev/disk/by-id/google-evidence-disk-1-20201204114002-d8f1d504-copy successfully attached
[INFO] Running ['lsblk', '/dev/disk/by-id/google-evidence-disk-1-20201204114002-d8f1d504-copy-part15', '-f', '-o', 
'FSTYPE', '-n']
[ERROR] Error running preprocessor for evidence-disk-1-20201204114002-d8f1d504-copy: /dev/disk/by-id/google-evidenc
e-disk-1-20201204114002-d8f1d504-copy-part15 should contain exactly one partition, found 0
[ERROR] DockerContainersEnumerationTask Task failed with exception: [Evidence GoogleCloudDisk:evidence-disk-1-20201
204114002-d8f1d504-copy:None being processed by Task DockerContainersEnumerationTask requires Evidence to be in sta
te MOUNTED, but earlier pre-processors may have failed.  Current state is [MOUNTED: False, ATTACHED: True, PARENT_M
OUNTED: False, PARENT_ATTACHED: False, DECOMPRESSED: False, DOCKER_MOUNTED: False]. See previous logs for more info
rmation.]
[ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/workers/__init__.py", line 744,
 in run_wrapper
    self.evidence_setup(evidence)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819-py3.6.egg/turbinia/workers/__init__.py", line 465,
 in evidence_setup
    evidence, self.name, state.name, evidence.format_state()))
turbinia.TurbiniaException: Evidence GoogleCloudDisk:evidence-disk-1-20201204114002-d8f1d504-copy:None being proces
sed by Task DockerContainersEnumerationTask requires Evidence to be in state MOUNTED, but earlier pre-processors ma
y have failed.  Current state is [MOUNTED: False, ATTACHED: True, PARENT_MOUNTED: False, PARENT_ATTACHED: False, DE
COMPRESSED: False, DOCKER_MOUNTED: False]. See previous logs for more information.

```

**Comment by hacktobeer** [comment]
preprocessor seems to error out as input google cloud disk contains 0 partitions.

```
# fdisk /dev/sdb

Welcome to fdisk (util-linux 2.33.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

GPT PMBR size mismatch (4612095 != 20971519) will be corrected by write.
The backup GPT table is not on the end of the device. This problem will be corrected by write.

Command (m for help): p

Disk /dev/sdb: 10 GiB, 10737418240 bytes, 20971520 sectors
Disk model: PersistentDisk  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: ABA5FCE2-6C6B-45AB-9226-D3D269D6ECB6

Device      Start     End Sectors  Size Type
/dev/sdb1  227328 4612062 4384735  2.1G Linux filesystem
/dev/sdb14   2048   10239    8192    4M BIOS boot
/dev/sdb15  10240  227327  217088  106M EFI System
```

**Comment by hacktobeer** [comment]
```
root@instance-1:/home/ramsesdebeer# lsblk /dev/sdb -f -o FSTYPE -n

ext4

vfat
root@instance-1:/home/ramsesdebeer# lsblk /dev/disk/by-id/
google-disk-1                                  google-instance-1-part14                       scsi-0Google_PersistentDisk_instance-1
google-disk-1-part1                            google-instance-1-part15                       scsi-0Google_PersistentDisk_instance-1-part1
google-disk-1-part14                           scsi-0Google_PersistentDisk_disk-1             scsi-0Google_PersistentDisk_instance-1-part14
google-disk-1-part15                           scsi-0Google_PersistentDisk_disk-1-part1       scsi-0Google_PersistentDisk_instance-1-part15
google-instance-1                              scsi-0Google_PersistentDisk_disk-1-part14      
google-instance-1-part1                        scsi-0Google_PersistentDisk_disk-1-part15      
root@instance-1:/home/ramsesdebeer# lsblk /dev/disk/by-id/google-disk-1
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdb       8:16   0   10G  0 disk 
├─sdb1    8:17   0  2.1G  0 part 
├─sdb14   8:30   0    4M  0 part 
└─sdb15   8:31   0  106M  0 part 
root@instance-1:/home/ramsesdebeer# lsblk /dev/disk/by-id/google-disk-1
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdb       8:16   0   10G  0 disk 
├─sdb1    8:17   0  2.1G  0 part 
├─sdb14   8:30   0    4M  0 part 
└─sdb15   8:31   0  106M  0 part 
# lsblk /dev/disk/by-id/google-disk-1-part15 -f -o FSTYPE -n
vfat
```

**Comment by aarontp** [comment]
I think there are a couple different things going on here.  The first one is that it's trying to act on partition 15 instead of partition 1.  It looks like the output from `glob.glob()` is arbitrary, and maybe since the partition count is double digits, it happens to be giving a different order.  It seems to return the sorted order in my testing even with double digit partitions, but even so we should add a sort in there to make sure it's doing what we expect. 

The second issue is that even though it is working on the 15th  partition, it still should have been able to enumerate the filesystem  and mount it.  I'm not sure why it couldn't do that, but I'll add a debug message there, and maybe increase the wait time after we attach the disk.

FTR, this code will actually be going away soon anyway in favor of the new partition enumeration with dfVFS.  There will be a new GoogleCloudDiskPartition evidence type that gets generated.

**Comment by aarontp** [comment]
Created https://github.com/google/turbinia/pull/674 for this.

**Comment by aarontp** [comment]
I think #674 will help with this, so I'm going to close this for now.  If this comes up again, please reopen the issue.  Thanks!
