### ISSUE TITLE
Adding errors to TurbiniaTaskResult causes it to be unpickleable

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#70]
[INFO]  Took 0.27 sec
Traceback (most recent call last):
  File "/home/turbinia/src/turbinia/turbiniactl", line 175, in <module>
    worker.listen()
  File "/home/turbinia/turbinia-env/local/lib/python2.7/site-packages/psq/worker.py", line 60, in listen
    self.run_task(task)
  File "/home/turbinia/turbinia-env/local/lib/python2.7/site-packages/psq/worker.py", line 69, in run_task
    task.execute(self.queue)
  File "/home/turbinia/turbinia-env/local/lib/python2.7/site-packages/psq/task.py", line 96, in execute
    queue.storage.put_task(self)
  File "/home/turbinia/turbinia-env/local/lib/python2.7/site-packages/psq/datastore_storage.py", line 61, in put_task
    entity['data'] = dumps(task)
  File "/home/turbinia/turbinia-env/local/lib/python2.7/site-packages/google/cloud/client.py", line 134, in __getstate__
    'Clients have non-trivial state that is local and unpickleable.',
pickle.PicklingError: Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.

**Comment by aarontp** [comment]
It turns out that it's not because the errors make it unpickleable, it's because there is no result object when there are exceptions that are not caught.
