### ISSUE TITLE
client requires dfvfs.....

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#722]
We should remove the dfvfs dependency for the client on dfvfs.

```
Executing googlecloudisk e2e test....this takes ~60 minutes!
[INFO] Turbinia version: 20210208
[DEBUG] Returning cached config from /root/.turbiniarc instead of reloading config
[DEBUG] Returning cached config from /root/.turbiniarc instead of reloading config
Traceback (most recent call last):
  File "/root/turbinia/bin/turbiniactl", line 8, in <module>
    sys.exit(main())
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/turbiniactl.py", line 445, in main
    from turbinia import client as TurbiniaClientProvider
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/client.py", line 39, in <module>
    from turbinia import task_manager
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/task_manager.py", line 30, in <module>
    from turbinia.jobs import manager as jobs_manager
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/jobs/__init__.py", line 26, in <module>
    from turbinia.jobs import partitions
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/jobs/partitions.py", line 23, in <module>
    from turbinia.workers.partitions import PartitionEnumerationTask
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/workers/partitions.py", line 20, in <module>
    from turbinia.lib import dfvfs_classes
  File "/root/turbinia/lib/python3.6/site-packages/turbinia/lib/dfvfs_classes.py", line 19, in <module>
    from dfvfs.helpers import volume_scanner
ModuleNotFoundError: No module named 'dfvfs'
```

**Comment by hacktobeer** [comment]
https://github.com/google/turbinia/blob/b89ee9a72cbb8f2a1db727c5656b9a442424107d/turbinia/workers/partitions.py#L20

Should be moved down to where the worker role is checked.

**Comment by hacktobeer** [comment]
Actually, the import is already there so line 20 can be removed.

https://github.com/google/turbinia/blob/b89ee9a72cbb8f2a1db727c5656b9a442424107d/turbinia/workers/partitions.py#L33

**Comment by hacktobeer** [comment]
you can reproduce by pip install turbinia in virtual env and exectuing eg turbiniactl status -i
