### ISSUE TITLE
Update google-cloud-logging package

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#739]
We need to use version >= 2 because of dftimewolf dependencies, and we need to use <=2.0.2 for the google cloud error package, but when trying to use that version I get the following:

```
$ turbiniactl -d server
Traceback (most recent call last):
  File "/home/aaronpeterson/.local/share/virtualenvs/turbinia-aeSTftCa/bin/turbiniactl", line 11, in <module>
    load_entry_point('turbinia', 'console_scripts', 'turbiniactl')()
  File "/home/aaronpeterson/src/turbinia/turbinia/turbiniactl.py", line 428, in main
    from turbinia.lib import google_cloud
  File "/home/aaronpeterson/src/turbinia/turbinia/lib/google_cloud.py", line 33, in <module>
    from google.cloud.logging import _helpers
ImportError: cannot import name '_helpers' from 'google.cloud.logging' (/home/aaronpeterson/.local/share/virtualenvs/turbinia-aeSTftCa/lib/python3.8/site-packages/google/cloud/logging/__init__.py)
```

**Comment by aarontp** [comment]
@alimez is this something you might be able to take a look at?

**Comment by aarontp** [comment]
@tomchop If we pin this to <= 2.0.2 is that going to be compatible with what you need for dftimewolf?

**Comment by tomchop** [comment]
Yes, anything > 2 should work!
