### ISSUE TITLE
Turbinia worker fails when DOCKER_ENABLED=True and there is no docker deamon

### ISSUE THREAD

**Issue by alimez** [google/turbinia#758]
Add exception handling to docker code to avoid breakage Stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/turbiniactl", line 33, in <module>
    sys.exit(load_entry_point('turbinia==20210208.3', 'console_scripts', 'turbiniactl')())
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.3-py3.6.egg/turbinia/turbiniactl.py", line 662, in main
    jobs_denylist=args.jobs_denylist, jobs_allowlist=args.jobs_allowlist)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.3-py3.6.egg/turbinia/client.py", line 1261, in __init__
    check_docker_dependencies(dependencies)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.3-py3.6.egg/turbinia/client.py", line 145, in check_docker_dependencies
    images = docker_manager.DockerManager().list_images(return_filter='short_id')
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.3-py3.6.egg/turbinia/lib/docker_manager.py", line 84, in __init__
    self.client = self._create_client()
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.3-py3.6.egg/turbinia/lib/docker_manager.py", line 99, in _create_client
    docker_client = docker.from_env()
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 222, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by alimez** [comment]
Add exception around https://github.com/google/turbinia/blob/508c796ff2ea2dd7e4ba7b1cfdc1e5fd7db2cc97/turbinia/client.py#L145

**Comment by hacktobeer** [comment]
This happens when DOCKER_ENABLED=True, there is no docker daemon installed. In this case the code will try to connect to the docker manager, urllib will retry and docker will think it's in error and restart itself creating a loop of error/restart
