### ISSUE TITLE
dockerexplorer task fails when no docker daemon is present

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#764]
```
2021-02-25 11:09:25 [INFO] Running sudo /usr/local/bin/de.py -d -r /tmp/turbinia-mounts/turbinia9ymlj8vj/var/lib/docker list all_containers
2021-02-25 11:09:25,755 [DEBUG] (MainProcess) PID:84 <de> /tmp/turbinia-mounts/turbinia9ymlj8vj/var/lib/docker is not a Docker directory
Error: -25 11:09:25,755 [ERROR] (MainProcess) PID:84 <de> Please specify a proper Docker directory path.
	hint: de.py -r /var/lib/docker
Error: -25 11:09:25 [ERROR] DockerContainersEnumerationTask Task failed with exception: [Expecting value: line 1 column 1 (char 0)]
Error: -25 11:09:25 [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819.4.dev180+g23bad94-py3.6.egg/turbinia/workers/__init__.py", line 798, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819.4.dev180+g23bad94-py3.6.egg/turbinia/workers/docker.py", line 107, in run
    containers_info = self.GetContainers(evidence)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20190819.4.dev180+g23bad94-py3.6.egg/turbinia/workers/docker.py", line 84, in GetContainers
    containers_info = json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

We need to add better exceptions in the docker.py task. Also see #758

**Comment by aarontp** [comment]
AFAIK, the docker daemon shouldn't need to be present for docker-explorer.  It looks to me like this is because of a path not existing for some reason.  Maybe the path is in the config, but not actually existent?   If that's the case, then we should filter that out at enumeration time (prior to when the Evidence is being used/mounted here).  Also, isn't this the same as https://github.com/google/turbinia/issues/747 ?

**Comment by aarontp** [comment]
(Ignore the last comment, I see your PR for this and I'll comment there)
