### ISSUE TITLE
Loop devices not available in dev containers

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#771]
I'm guessing we need to add a container mount for /dev or something similar.

```
# losetup --show --find -r /evidence/test-small.img
losetup: cannot find an unused loop device

# ls -al /dev/loop*
ls: cannot access '/dev/loop*': No such file or directory
```

Full trace
```
2021-02-27 01:50:05 [INFO] Starting Task PartitionEnumerationTask ef6523d455ed40b1933de0226e08f798
2021-02-27 01:50:05 [DEBUG] Starting pre-processor for evidence /evidence/test-small.img
2021-02-27 01:50:05 [INFO] Running command sudo losetup --show --find -r /evidence/test-small.img
losetup: cannot find an unused loop device
2021-02-27 01:50:05 [ERROR] Error running preprocessor for /evidence/test-small.img: Could not set losetup devices Command '['sudo', 'losetup', '--show', '--find', '-r', '/evidence/test-small.img']' returned non-zero exit status 1.
2021-02-27 01:50:05 [DEBUG] Pre-processing evidence /evidence/test-small.img is complete, and evidence is in state [MOUNTED: False, ATTACHED: False, DECOMPRESSED: False]
2021-02-27 01:50:05 [ERROR] PartitionEnumerationTask Task failed with exception: [Evidence RawDisk:/evidence/test-small.img:/evidence/test-small.img being processed by Task PartitionEnumerationTask requires Evidence to be in state ATTACHED, but earlier pre-processors may have failed.  Current state is [MOUNTED: False, ATTACHED: False, DECOMPRESSED: False]. See previous logs for more information.]
2021-02-27 01:50:05 [ERROR] Traceback (most recent call last):
  File "/workspaces/turbinia/turbinia/workers/__init__.py", line 796, in run_wrapper
    self.evidence_setup(evidence)
  File "/workspaces/turbinia/turbinia/workers/__init__.py", line 506, in evidence_setup
    evidence, self.name, state.name, evidence.format_state()))
turbinia.TurbiniaException: Evidence RawDisk:/evidence/test-small.img:/evidence/test-small.img being processed by Task PartitionEnumerationTask requires Evidence to be in state ATTACHED, but earlier pre-processors may have failed.  Current state is [MOUNTED: False, ATTACHED: False, DECOMPRESSED: False]. See previous logs for more information.
```

**Comment by hacktobeer** [comment]
Where's the container running? Loop devices in containers are only
compatible on a Linux host OS.

**Comment by aarontp** [comment]
This is from running the containers on my Linux laptop.

**Comment by hacktobeer** [comment]
Running it through the docker compose configuration so the container runs
privileged?

**Comment by hacktobeer** [comment]
Oh and make sure your loop devices are actually there in the Linux host OS
of course.

**Comment by aarontp** [comment]
I made sure I was a member of the `docker` group and let VS Code start everything up (though I had to manually start Redis).  Should I start it with `docker-compose` then?  Any special flags I need?

Yes, the loop devices are available on the linux host.

Thanks!

**Comment by hacktobeer** [comment]
Oh wait, you are using the vscode devcontainer, correct? Let me have a look
today as that's fully based on the latest dev image from Google Cloud.

**Comment by hacktobeer** [comment]
devcontainer was not starting in privileged mode so no loop devices from host were exposed in container.
https://github.com/google/turbinia/pull/777
