### ISSUE TITLE
Prometheus Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#774]
The second time a Task runs with the same name, the prometheus code errors out due to duplicate timeseries:

```
2021-03-02 00:57:10 [INFO] Starting Task PartitionEnumerationTask 84181e3126ca4fa5ba2acda57d93322c
[2021-03-02 00:57:10,236: INFO/MainProcess] Lock 140581005659272 released on /evidence/turbinia-worker.lock
[2021-03-02 00:57:10,241: ERROR/MainProcess] Task task_runner[3de967e0-099d-430c-a1a0-1b635681ab78] raised unexpected: ValueError("Duplicated timeseries in CollectorRegistry: {'PartitionEnumerationTask_duration_seconds_created', 'PartitionEnumerationTask_duration_seconds_count', 'PartitionEnumerationTask_duration_seconds_bucket', 'PartitionEnumerationTask_duration_seconds', 'PartitionEnumerationTask_duration_seconds_sum'}",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/workspaces/turbinia/turbinia/task_manager.py", line 97, in task_runner
    return obj.run_wrapper(*args, **kwargs)
  File "/workspaces/turbinia/turbinia/workers/__init__.py", line 785, in run_wrapper
    'Seconds to run {0:s}'.format(self.name))
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/metrics.py", line 517, in __init__
    labelvalues=labelvalues,
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/metrics.py", line 121, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/registry.py", line 31, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'PartitionEnumerationTask_duration_seconds_created', 'PartitionEnumerationTask_duration_seconds_count', 'PartitionEnumerationTask_duration_seconds_bucket', 'PartitionEnumerationTask_duration_seconds', 'PartitionEnumerationTask_duration_seconds_sum'}
```

**Comment by aarontp** [comment]
@alimez Could you take a look at this one?

**Comment by hacktobeer** [comment]
this is impacting current e2e tests as well as it makes the FileExtractionTask fail (and all upstream tasks as such).
