### ISSUE TITLE
Unable to retrieve logical volume

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#790]
```
PartitionEnumerationTask Task failed with exception: [pyvslvm_volume_group_get_logical_volume_by_index: unable to retrieve logical volume: 0. libvslvm_logical_volume_initialize: unsupported number of stripes. libvslvm_volume_group_get_logical_volume: unable to create logical volume.]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.4.dev19+g7c02e5e-py3.6.egg/turbinia/workers/__init__.py", line 893, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.4.dev19+g7c02e5e-py3.6.egg/turbinia/workers/partitions.py", line 144, in run
    path_specs = partitions.Enumerate(evidence)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210208.4.dev19+g7c02e5e-py3.6.egg/turbinia/processors/partitions.py", line 47, in Enumerate
    path_specs = scanner.GetBasePathSpecs(evidence.local_path)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/volume_scanner.py", line 594, in GetBasePathSpecs
    self._source_scanner.Scan(scan_context)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/source_scanner.py", line 661, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/source_scanner.py", line 479, in _ScanNode
    scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/source_scanner.py", line 606, in _ScanVolumeSystemRootNode
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/vfs/lvm_file_entry.py", line 101, in _GetSubFileEntries
    yield LVMFileEntry(self._resolver_context, self._file_system, path_spec)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/vfs/lvm_file_entry.py", line 65, in __init__
    path_spec)
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/vfs/lvm_file_system.py", line 133, in GetLVMLogicalVolumeByPathSpec
    return self._vslvm_volume_group.get_logical_volume(volume_index)
OSError: pyvslvm_volume_group_get_logical_volume_by_index: unable to retrieve logical volume: 0. libvslvm_logical_volume_initialize: unsupported number of stripes. libvslvm_volume_group_get_logical_volume: unable to create logical volume.

No state_manager initialized, not updating Task info
Trying last ditch attempt to close result
Task Result was auto-closed from task executor on turbinia-worker-6eaf93e7aee7c9cf-0 likely due to previous failures.  Previous status: [PartitionEnumerationTask Task failed with exception: [pyvslvm_volume_group_get_logical_volume_by_index: unable to retrieve logical volume: 0. libvslvm_logical_volume_initialize: unsupported number of stripes. libvslvm_volume_group_get_logical_volume: unable to create logical volume.]]
```

**Comment by aarontp** [comment]
FYI @dfjxs

**Comment by dfjxs** [comment]
libvslvm (https://github.com/libyal/libvslvm) currently only supports simple LVM volumes.

This image used for testing is not supported.

**Comment by aarontp** [comment]
Is this something that we can determine at enumeration time and issue some kind of warning then?

**Comment by aarontp** [comment]
I filed this bug for upstream support for non-simple LVM volumes: https://github.com/libyal/libvslvm/issues/11

**Comment by aarontp** [comment]
I think we can close this out and rely on the upstream bug to fix this.
