### ISSUE TITLE
DockerContainersEnumerationTask JSON decode failure

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#810]
```
DockerContainersEnumerationTask Task failed with exception: [Expecting value: line 1 column 1 (char 0)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210423.dev2+g1f137be-py3.6.egg/turbinia/workers/__init__.py", line 895, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210423.dev2+g1f137be-py3.6.egg/turbinia/workers/docker.py", line 107, in run
    containers_info = self.GetContainers(evidence)
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210423.dev2+g1f137be-py3.6.egg/turbinia/workers/docker.py", line 84, in GetContainers
    containers_info = json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

e2e test -> https://plaso-ci.log2timeline.net/jenkins/view/Turbinia/job/turbinia-e2e-googleclouddisk-dev/59/

**Comment by hacktobeer** [comment]
So this tries to load the json output from de.py but fails if it's not JSON. As we can't control the actual output of the command we need to make sure this json deseriaizing is in a try/except block.
