### ISSUE TITLE
Partition enumeration failing on googleclouddisks

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#821]
``` 
2021-05-31 13:46:43 [ERROR] PartitionEnumerationTask Task failed with exception: [Could not enumerate partitions [/dev/disk/by-id/google-evidence-cluster-108d-w-1-20210526120927-acd4cb17-copy]: Volume missing for identifier: p2.]                                     
2021-05-31 13:46:43 [INFO] Traceback (most recent call last):                                                                        
  File "/usr/local/lib/python3.6/dist-packages/turbinia-20210503-py3.6.egg/turbinia/processors/partitions.py", line 48, in Enumerate 
    path_specs = scanner.GetBasePathSpecs(evidence.local_path)                                                                       
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/volume_scanner.py", line 621, in GetBasePathSpecs                       
    partition_identifiers = self._GetPartitionIdentifiers(scan_node, options)                                                        
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/volume_scanner.py", line 254, in _GetPartitionIdentifiers               
    prefix=volume_system.VOLUME_IDENTIFIER_PREFIX)                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/dfvfs/helpers/volume_scanner.py", line 400, in _NormalizedVolumeIdentifiers           
    'Volume missing for identifier: {0:s}.'.format(volume_identifier))                                                               
dfvfs.lib.errors.ScannerError: Volume missing for identifier: p2.  
```

**Comment by joachimmetz** [comment]
Looks like dfvfs is expecting `p14` as identifier but the Turbinia mediator returns `p2` 
https://github.com/google/turbinia/blob/f9da5894a120eb55353a6af2c6d52f1d9a862777/turbinia/lib/dfvfs_classes.py#L81
