### ISSUE TITLE
GCF calls are failing on GCP deployment

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#843]
Calls to get the status of a request (getasks GCF) from Turbinia on Cloud are failing.

```
Accessing deprecated metadata server endpoint at "/computeMetadata/v1beta1/instance/service-accounts/default/token" from user-agent "google-api-nodejs-client/0.10.0"
```

```
Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: Could not refresh access token.
    at Object.exports.createStatusError (/workspace/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/workspace/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/workspace/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/workspace/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/workspace/node_modules/grpc/src/client_interceptors.js:847:24)
```

```
Error: Process exited with code 16
    at process.on.code (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:275:22)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at process.exit (internal/process/per_thread.js:168:15)
    at Object.sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:37:9)
    at process.on.err (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:271:22)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by hacktobeer** [comment]
Ideas:
* is this because we user an older Nodejs runtime engine (v10)?
* is this because our GCF python library is too old and trying to reach out to older metadata endpoint?

**Comment by hacktobeer** [comment]
Okay, so the issue is the first line, our code tries to refresh the token using the v1beta1 of the metadata server while it should be using v1. 

```
Accessing deprecated metadata server endpoint at "/computeMetadata/v1beta1/instance/service-accounts/default/token" from user-agent "google-api-nodejs-client/0.10.0"
```

**Comment by hacktobeer** [comment]
Okay, so I dug in and fixed it by:
* delete the appspot service account
* create a new one
* assign the cloud functions to run under the new one

When creating a service account an metadata api endpoint is assigned and can not be changed. During the upgrade from v1beta1 for the api metadata endpoint to v1 the AppEngine (under which cloud functions run) service account went in error and could not refresh its token anymore as it still tried to talk to the v1beta1 metadata end point.
