### ISSUE TITLE
Recipe validation fails

### ISSUE THREAD

**Issue by anttitikkanen** [google/turbinia#943]
When trying to submit a recipe over turbiniactl, the recipe validation fails:

turbiniactl -P ./temp/recipe.yaml googleclouddisk -d disk-name

2021-11-19 09:48:04 [INFO] Turbinia version: 20211018
2021-11-19 09:48:16 [INFO] Disabling non-allowlisted jobs configured to be disabled in the config file: binaryextractorjob, bulkextractorjob, dfdeweyjob, hindsightjob, photorecjob, jenkinsanalysisjob, volatilityjob
2021-11-19 09:48:16 [INFO] Loading recipe file from ./temp/recipe.yaml
Traceback (most recent call last):
  File "/usr/local/bin/turbiniactl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/turbinia/turbiniactl.py", line 824, in main
    recipe_dict = recipe_helpers.load_recipe_from_file(
  File "/usr/local/lib/python3.9/site-packages/turbinia/lib/recipe_helpers.py", line 60, in load_recipe_from_file
    success, _ = validate_recipe(recipe_dict)
  File "/usr/local/lib/python3.9/site-packages/turbinia/lib/recipe_helpers.py", line 161, in validate_recipe
    if not task_loader.check_task_name(proposed_task):
  File "/usr/local/lib/python3.9/site-packages/turbinia/task_utils.py", line 82, in check_task_name
    for task in TASK_LIST:
NameError: name 'TASK_LIST' is not defined

Bug is also present in master branch, this should be "self.TASK_LIST":

https://github.com/google/turbinia/blob/54c2a03566422efffcc93197661d6e5da319e591/turbinia/task_utils.py#L82

Would send a PR myself, but still getting approvals to contribute :)

**Comment by aarontp** [comment]
Thanks for the report.  I fixed this in https://github.com/google/turbinia/pull/944 and added some tests for this file as well.
