### ISSUE TITLE
Request had invalid authentication credentials

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#95]
I fairly frequently see errors like "Request had invalid authentication credentials" when I have a worker running for more than a few hours.

I filed a bug against PSQ for this (https://github.com/GoogleCloudPlatform/psq/issues/31), but I'm adding this here so we can also track this since it affects Turbinia, and others may run into the same problem.  This affects the server and the worker.

Here is a full stack-trace:
Traceback (most recent call last):
  File "./turbiniactl", line 271, in <module>
    elif args.command == 'psqworker':
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/psq/worker.py", line 94, in listen
    super(MultiprocessWorker, self).listen()
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/psq/worker.py", line 53, in listen
    tasks = self._safe_dequeue()
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/psq/worker.py", line 46, in _safe_dequeue
    return inner()
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/psq/worker.py", line 45, in inner
    return self.queue.dequeue(max=self.tasks_per_poll, block=True)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/psq/queue.py", line 104, in dequeue
    return_immediately=not block, max_messages=max)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/cloud/pubsub/subscription.py", line 365, in pull
    self.full_name, return_immediately, max_messages)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/cloud/pubsub/_gax.py", line 437, in subscription_pull
    return_immediately=return_immediately)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/cloud/gapic/pubsub/v1/subscriber_client.py", line 706, in pull
    return self._pull(request, options)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 428, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 416, in base_caller
    return api_call(*args)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/google/home/aaronpeterson/src/psq-env/local/lib/python2.7/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: GaxError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.UNAUTHENTICATED, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.)>)

**Comment by aarontp** [comment]
This seems to be fixed with more recent versions.
